name: Pipeline

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

jobs:

  Site:
    runs-on: ubuntu-latest
    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v3

      - uses: ./.github/site
